// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.policy.v1.policy

sealed abstract class SecondFactorType(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = SecondFactorType
  def isSecondFactorTypeUnspecified: _root_.scala.Boolean = false
  def isSecondFactorTypeOtp: _root_.scala.Boolean = false
  def isSecondFactorTypeU2F: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[SecondFactorType] = com.zitadel.policy.v1.policy.SecondFactorType
  final def asRecognized: _root_.scala.Option[com.zitadel.policy.v1.policy.SecondFactorType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[com.zitadel.policy.v1.policy.SecondFactorType.Recognized])
}

object SecondFactorType extends _root_.scalapb.GeneratedEnumCompanion[SecondFactorType] {
  sealed trait Recognized extends SecondFactorType
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[SecondFactorType] = this
  
  @SerialVersionUID(0L)
  case object SECOND_FACTOR_TYPE_UNSPECIFIED extends SecondFactorType(0) with SecondFactorType.Recognized {
    val index = 0
    val name = "SECOND_FACTOR_TYPE_UNSPECIFIED"
    override def isSecondFactorTypeUnspecified: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SECOND_FACTOR_TYPE_OTP extends SecondFactorType(1) with SecondFactorType.Recognized {
    val index = 1
    val name = "SECOND_FACTOR_TYPE_OTP"
    override def isSecondFactorTypeOtp: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SECOND_FACTOR_TYPE_U2F extends SecondFactorType(2) with SecondFactorType.Recognized {
    val index = 2
    val name = "SECOND_FACTOR_TYPE_U2F"
    override def isSecondFactorTypeU2F: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends SecondFactorType(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(SECOND_FACTOR_TYPE_UNSPECIFIED, SECOND_FACTOR_TYPE_OTP, SECOND_FACTOR_TYPE_U2F)
  def fromValue(__value: _root_.scala.Int): SecondFactorType = __value match {
    case 0 => SECOND_FACTOR_TYPE_UNSPECIFIED
    case 1 => SECOND_FACTOR_TYPE_OTP
    case 2 => SECOND_FACTOR_TYPE_U2F
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = PolicyProto.javaDescriptor.getEnumTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = PolicyProto.scalaDescriptor.enums(0)
}