services:
  postgres:
    restart: always
    image: postgres:14-alpine
    ports:
      - "2345:5432"
    environment:
      POSTGRES_DB: office_buddy
      POSTGRES_PASSWORD: postgres
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5