// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.app.v1.app

@SerialVersionUID(0L)
final case class APIConfig(
    clientId: _root_.scala.Predef.String = "",
    authMethodType: com.zitadel.app.v1.app.APIAuthMethodType = com.zitadel.app.v1.app.APIAuthMethodType.API_AUTH_METHOD_TYPE_BASIC,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[APIConfig] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = clientId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = authMethodType.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(3, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = clientId
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = authMethodType.value
        if (__v != 0) {
          _output__.writeEnum(3, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withClientId(__v: _root_.scala.Predef.String): APIConfig = copy(clientId = __v)
    def withAuthMethodType(__v: com.zitadel.app.v1.app.APIAuthMethodType): APIConfig = copy(authMethodType = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = clientId
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = authMethodType.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(clientId)
        case 3 => _root_.scalapb.descriptors.PEnum(authMethodType.scalaValueDescriptor)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: com.zitadel.app.v1.app.APIConfig.type = com.zitadel.app.v1.app.APIConfig
    // @@protoc_insertion_point(GeneratedMessage[zitadel.app.v1.APIConfig])
}

object APIConfig extends scalapb.GeneratedMessageCompanion[com.zitadel.app.v1.app.APIConfig] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.zitadel.app.v1.app.APIConfig] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.zitadel.app.v1.app.APIConfig = {
    var __clientId: _root_.scala.Predef.String = ""
    var __authMethodType: com.zitadel.app.v1.app.APIAuthMethodType = com.zitadel.app.v1.app.APIAuthMethodType.API_AUTH_METHOD_TYPE_BASIC
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __clientId = _input__.readStringRequireUtf8()
        case 24 =>
          __authMethodType = com.zitadel.app.v1.app.APIAuthMethodType.fromValue(_input__.readEnum())
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    com.zitadel.app.v1.app.APIConfig(
        clientId = __clientId,
        authMethodType = __authMethodType,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.zitadel.app.v1.app.APIConfig] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      com.zitadel.app.v1.app.APIConfig(
        clientId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        authMethodType = com.zitadel.app.v1.app.APIAuthMethodType.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(com.zitadel.app.v1.app.APIAuthMethodType.API_AUTH_METHOD_TYPE_BASIC.scalaValueDescriptor).number)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = AppProto.javaDescriptor.getMessageTypes().get(5)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = AppProto.scalaDescriptor.messages(5)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 3 => com.zitadel.app.v1.app.APIAuthMethodType
    }
  }
  lazy val defaultInstance = com.zitadel.app.v1.app.APIConfig(
    clientId = "",
    authMethodType = com.zitadel.app.v1.app.APIAuthMethodType.API_AUTH_METHOD_TYPE_BASIC
  )
  implicit class APIConfigLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.app.v1.app.APIConfig]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.zitadel.app.v1.app.APIConfig](_l) {
    def clientId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.clientId)((c_, f_) => c_.copy(clientId = f_))
    def authMethodType: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.app.v1.app.APIAuthMethodType] = field(_.authMethodType)((c_, f_) => c_.copy(authMethodType = f_))
  }
  final val CLIENT_ID_FIELD_NUMBER = 1
  final val AUTH_METHOD_TYPE_FIELD_NUMBER = 3
  def of(
    clientId: _root_.scala.Predef.String,
    authMethodType: com.zitadel.app.v1.app.APIAuthMethodType
  ): _root_.com.zitadel.app.v1.app.APIConfig = _root_.com.zitadel.app.v1.app.APIConfig(
    clientId,
    authMethodType
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[zitadel.app.v1.APIConfig])
}
