// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.user.v2alpha.user_service

@SerialVersionUID(0L)
final case class ListAuthenticationMethodTypesResponse(
    details: _root_.scala.Option[com.zitadel.`object`.v2alpha.`object`.ListDetails] = _root_.scala.None,
    authMethodTypes: _root_.scala.Seq[com.zitadel.user.v2alpha.user_service.AuthenticationMethodType] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ListAuthenticationMethodTypesResponse] {
    private[this] def authMethodTypesSerializedSize = {
      if (__authMethodTypesSerializedSizeField == 0) __authMethodTypesSerializedSizeField = {
        var __s: _root_.scala.Int = 0
        authMethodTypes.foreach(__i => __s += _root_.com.google.protobuf.CodedOutputStream.computeEnumSizeNoTag(__i.value))
        __s
      }
      __authMethodTypesSerializedSizeField
    }
    @transient private[this] var __authMethodTypesSerializedSizeField: _root_.scala.Int = 0
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      if (details.isDefined) {
        val __value = details.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (authMethodTypes.nonEmpty) {
        val __localsize = authMethodTypesSerializedSize
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__localsize) + __localsize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      details.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      if (authMethodTypes.nonEmpty) {
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(authMethodTypesSerializedSize)
        authMethodTypes.foreach((_output__.writeEnumNoTag _).compose((_: com.zitadel.user.v2alpha.user_service.AuthenticationMethodType).value))
      };
      unknownFields.writeTo(_output__)
    }
    def getDetails: com.zitadel.`object`.v2alpha.`object`.ListDetails = details.getOrElse(com.zitadel.`object`.v2alpha.`object`.ListDetails.defaultInstance)
    def clearDetails: ListAuthenticationMethodTypesResponse = copy(details = _root_.scala.None)
    def withDetails(__v: com.zitadel.`object`.v2alpha.`object`.ListDetails): ListAuthenticationMethodTypesResponse = copy(details = Option(__v))
    def clearAuthMethodTypes = copy(authMethodTypes = _root_.scala.Seq.empty)
    def addAuthMethodTypes(__vs: com.zitadel.user.v2alpha.user_service.AuthenticationMethodType *): ListAuthenticationMethodTypesResponse = addAllAuthMethodTypes(__vs)
    def addAllAuthMethodTypes(__vs: Iterable[com.zitadel.user.v2alpha.user_service.AuthenticationMethodType]): ListAuthenticationMethodTypesResponse = copy(authMethodTypes = authMethodTypes ++ __vs)
    def withAuthMethodTypes(__v: _root_.scala.Seq[com.zitadel.user.v2alpha.user_service.AuthenticationMethodType]): ListAuthenticationMethodTypesResponse = copy(authMethodTypes = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => details.orNull
        case 2 => authMethodTypes.iterator.map(_.javaValueDescriptor).toSeq
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => details.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => _root_.scalapb.descriptors.PRepeated(authMethodTypes.iterator.map(__e => _root_.scalapb.descriptors.PEnum(__e.scalaValueDescriptor)).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: com.zitadel.user.v2alpha.user_service.ListAuthenticationMethodTypesResponse.type = com.zitadel.user.v2alpha.user_service.ListAuthenticationMethodTypesResponse
    // @@protoc_insertion_point(GeneratedMessage[zitadel.user.v2alpha.ListAuthenticationMethodTypesResponse])
}

object ListAuthenticationMethodTypesResponse extends scalapb.GeneratedMessageCompanion[com.zitadel.user.v2alpha.user_service.ListAuthenticationMethodTypesResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.zitadel.user.v2alpha.user_service.ListAuthenticationMethodTypesResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.zitadel.user.v2alpha.user_service.ListAuthenticationMethodTypesResponse = {
    var __details: _root_.scala.Option[com.zitadel.`object`.v2alpha.`object`.ListDetails] = _root_.scala.None
    val __authMethodTypes: _root_.scala.collection.immutable.VectorBuilder[com.zitadel.user.v2alpha.user_service.AuthenticationMethodType] = new _root_.scala.collection.immutable.VectorBuilder[com.zitadel.user.v2alpha.user_service.AuthenticationMethodType]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __details = Option(__details.fold(_root_.scalapb.LiteParser.readMessage[com.zitadel.`object`.v2alpha.`object`.ListDetails](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 16 =>
          __authMethodTypes += com.zitadel.user.v2alpha.user_service.AuthenticationMethodType.fromValue(_input__.readEnum())
        case 18 => {
          val length = _input__.readRawVarint32()
          val oldLimit = _input__.pushLimit(length)
          while (_input__.getBytesUntilLimit > 0) {
            __authMethodTypes += com.zitadel.user.v2alpha.user_service.AuthenticationMethodType.fromValue(_input__.readEnum())
          }
          _input__.popLimit(oldLimit)
        }
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    com.zitadel.user.v2alpha.user_service.ListAuthenticationMethodTypesResponse(
        details = __details,
        authMethodTypes = __authMethodTypes.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.zitadel.user.v2alpha.user_service.ListAuthenticationMethodTypesResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      com.zitadel.user.v2alpha.user_service.ListAuthenticationMethodTypesResponse(
        details = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[com.zitadel.`object`.v2alpha.`object`.ListDetails]]),
        authMethodTypes = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[_root_.scalapb.descriptors.EnumValueDescriptor]]).getOrElse(_root_.scala.Seq.empty).iterator.map(__e => com.zitadel.user.v2alpha.user_service.AuthenticationMethodType.fromValue(__e.number)).toSeq
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = UserServiceProto.javaDescriptor.getMessageTypes().get(31)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = UserServiceProto.scalaDescriptor.messages(31)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = com.zitadel.`object`.v2alpha.`object`.ListDetails
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 2 => com.zitadel.user.v2alpha.user_service.AuthenticationMethodType
    }
  }
  lazy val defaultInstance = com.zitadel.user.v2alpha.user_service.ListAuthenticationMethodTypesResponse(
    details = _root_.scala.None,
    authMethodTypes = _root_.scala.Seq.empty
  )
  implicit class ListAuthenticationMethodTypesResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.user.v2alpha.user_service.ListAuthenticationMethodTypesResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.zitadel.user.v2alpha.user_service.ListAuthenticationMethodTypesResponse](_l) {
    def details: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.`object`.v2alpha.`object`.ListDetails] = field(_.getDetails)((c_, f_) => c_.copy(details = Option(f_)))
    def optionalDetails: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.zitadel.`object`.v2alpha.`object`.ListDetails]] = field(_.details)((c_, f_) => c_.copy(details = f_))
    def authMethodTypes: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[com.zitadel.user.v2alpha.user_service.AuthenticationMethodType]] = field(_.authMethodTypes)((c_, f_) => c_.copy(authMethodTypes = f_))
  }
  final val DETAILS_FIELD_NUMBER = 1
  final val AUTH_METHOD_TYPES_FIELD_NUMBER = 2
  def of(
    details: _root_.scala.Option[com.zitadel.`object`.v2alpha.`object`.ListDetails],
    authMethodTypes: _root_.scala.Seq[com.zitadel.user.v2alpha.user_service.AuthenticationMethodType]
  ): _root_.com.zitadel.user.v2alpha.user_service.ListAuthenticationMethodTypesResponse = _root_.com.zitadel.user.v2alpha.user_service.ListAuthenticationMethodTypesResponse(
    details,
    authMethodTypes
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[zitadel.user.v2alpha.ListAuthenticationMethodTypesResponse])
}
