// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.user.v1.user

sealed abstract class Gender(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = Gender
  def isGenderUnspecified: _root_.scala.Boolean = false
  def isGenderFemale: _root_.scala.Boolean = false
  def isGenderMale: _root_.scala.Boolean = false
  def isGenderDiverse: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[Gender] = com.zitadel.user.v1.user.Gender
  final def asRecognized: _root_.scala.Option[com.zitadel.user.v1.user.Gender.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[com.zitadel.user.v1.user.Gender.Recognized])
}

object Gender extends _root_.scalapb.GeneratedEnumCompanion[Gender] {
  sealed trait Recognized extends Gender
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[Gender] = this
  
  @SerialVersionUID(0L)
  case object GENDER_UNSPECIFIED extends Gender(0) with Gender.Recognized {
    val index = 0
    val name = "GENDER_UNSPECIFIED"
    override def isGenderUnspecified: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GENDER_FEMALE extends Gender(1) with Gender.Recognized {
    val index = 1
    val name = "GENDER_FEMALE"
    override def isGenderFemale: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GENDER_MALE extends Gender(2) with Gender.Recognized {
    val index = 2
    val name = "GENDER_MALE"
    override def isGenderMale: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GENDER_DIVERSE extends Gender(3) with Gender.Recognized {
    val index = 3
    val name = "GENDER_DIVERSE"
    override def isGenderDiverse: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends Gender(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(GENDER_UNSPECIFIED, GENDER_FEMALE, GENDER_MALE, GENDER_DIVERSE)
  def fromValue(__value: _root_.scala.Int): Gender = __value match {
    case 0 => GENDER_UNSPECIFIED
    case 1 => GENDER_FEMALE
    case 2 => GENDER_MALE
    case 3 => GENDER_DIVERSE
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = UserProto.javaDescriptor.getEnumTypes().get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = UserProto.scalaDescriptor.enums(1)
}