// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.user.v1.user

@SerialVersionUID(0L)
final case class Profile(
    firstName: _root_.scala.Predef.String = "",
    lastName: _root_.scala.Predef.String = "",
    nickName: _root_.scala.Predef.String = "",
    displayName: _root_.scala.Predef.String = "",
    preferredLanguage: _root_.scala.Predef.String = "",
    gender: com.zitadel.user.v1.user.Gender = com.zitadel.user.v1.user.Gender.GENDER_UNSPECIFIED,
    avatarUrl: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Profile] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = firstName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = lastName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = nickName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = displayName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      
      {
        val __value = preferredLanguage
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      
      {
        val __value = gender.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(6, __value)
        }
      };
      
      {
        val __value = avatarUrl
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = firstName
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = lastName
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = nickName
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = displayName
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = preferredLanguage
        if (!__v.isEmpty) {
          _output__.writeString(5, __v)
        }
      };
      {
        val __v = gender.value
        if (__v != 0) {
          _output__.writeEnum(6, __v)
        }
      };
      {
        val __v = avatarUrl
        if (!__v.isEmpty) {
          _output__.writeString(7, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withFirstName(__v: _root_.scala.Predef.String): Profile = copy(firstName = __v)
    def withLastName(__v: _root_.scala.Predef.String): Profile = copy(lastName = __v)
    def withNickName(__v: _root_.scala.Predef.String): Profile = copy(nickName = __v)
    def withDisplayName(__v: _root_.scala.Predef.String): Profile = copy(displayName = __v)
    def withPreferredLanguage(__v: _root_.scala.Predef.String): Profile = copy(preferredLanguage = __v)
    def withGender(__v: com.zitadel.user.v1.user.Gender): Profile = copy(gender = __v)
    def withAvatarUrl(__v: _root_.scala.Predef.String): Profile = copy(avatarUrl = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = firstName
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = lastName
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = nickName
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = displayName
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = preferredLanguage
          if (__t != "") __t else null
        }
        case 6 => {
          val __t = gender.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 7 => {
          val __t = avatarUrl
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(firstName)
        case 2 => _root_.scalapb.descriptors.PString(lastName)
        case 3 => _root_.scalapb.descriptors.PString(nickName)
        case 4 => _root_.scalapb.descriptors.PString(displayName)
        case 5 => _root_.scalapb.descriptors.PString(preferredLanguage)
        case 6 => _root_.scalapb.descriptors.PEnum(gender.scalaValueDescriptor)
        case 7 => _root_.scalapb.descriptors.PString(avatarUrl)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: com.zitadel.user.v1.user.Profile.type = com.zitadel.user.v1.user.Profile
    // @@protoc_insertion_point(GeneratedMessage[zitadel.user.v1.Profile])
}

object Profile extends scalapb.GeneratedMessageCompanion[com.zitadel.user.v1.user.Profile] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.zitadel.user.v1.user.Profile] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.zitadel.user.v1.user.Profile = {
    var __firstName: _root_.scala.Predef.String = ""
    var __lastName: _root_.scala.Predef.String = ""
    var __nickName: _root_.scala.Predef.String = ""
    var __displayName: _root_.scala.Predef.String = ""
    var __preferredLanguage: _root_.scala.Predef.String = ""
    var __gender: com.zitadel.user.v1.user.Gender = com.zitadel.user.v1.user.Gender.GENDER_UNSPECIFIED
    var __avatarUrl: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __firstName = _input__.readStringRequireUtf8()
        case 18 =>
          __lastName = _input__.readStringRequireUtf8()
        case 26 =>
          __nickName = _input__.readStringRequireUtf8()
        case 34 =>
          __displayName = _input__.readStringRequireUtf8()
        case 42 =>
          __preferredLanguage = _input__.readStringRequireUtf8()
        case 48 =>
          __gender = com.zitadel.user.v1.user.Gender.fromValue(_input__.readEnum())
        case 58 =>
          __avatarUrl = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    com.zitadel.user.v1.user.Profile(
        firstName = __firstName,
        lastName = __lastName,
        nickName = __nickName,
        displayName = __displayName,
        preferredLanguage = __preferredLanguage,
        gender = __gender,
        avatarUrl = __avatarUrl,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.zitadel.user.v1.user.Profile] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      com.zitadel.user.v1.user.Profile(
        firstName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        lastName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        nickName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        displayName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        preferredLanguage = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        gender = com.zitadel.user.v1.user.Gender.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(com.zitadel.user.v1.user.Gender.GENDER_UNSPECIFIED.scalaValueDescriptor).number),
        avatarUrl = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = UserProto.javaDescriptor.getMessageTypes().get(3)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = UserProto.scalaDescriptor.messages(3)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 6 => com.zitadel.user.v1.user.Gender
    }
  }
  lazy val defaultInstance = com.zitadel.user.v1.user.Profile(
    firstName = "",
    lastName = "",
    nickName = "",
    displayName = "",
    preferredLanguage = "",
    gender = com.zitadel.user.v1.user.Gender.GENDER_UNSPECIFIED,
    avatarUrl = ""
  )
  implicit class ProfileLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.user.v1.user.Profile]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.zitadel.user.v1.user.Profile](_l) {
    def firstName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.firstName)((c_, f_) => c_.copy(firstName = f_))
    def lastName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.lastName)((c_, f_) => c_.copy(lastName = f_))
    def nickName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.nickName)((c_, f_) => c_.copy(nickName = f_))
    def displayName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.displayName)((c_, f_) => c_.copy(displayName = f_))
    def preferredLanguage: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.preferredLanguage)((c_, f_) => c_.copy(preferredLanguage = f_))
    def gender: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.user.v1.user.Gender] = field(_.gender)((c_, f_) => c_.copy(gender = f_))
    def avatarUrl: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.avatarUrl)((c_, f_) => c_.copy(avatarUrl = f_))
  }
  final val FIRST_NAME_FIELD_NUMBER = 1
  final val LAST_NAME_FIELD_NUMBER = 2
  final val NICK_NAME_FIELD_NUMBER = 3
  final val DISPLAY_NAME_FIELD_NUMBER = 4
  final val PREFERRED_LANGUAGE_FIELD_NUMBER = 5
  final val GENDER_FIELD_NUMBER = 6
  final val AVATAR_URL_FIELD_NUMBER = 7
  def of(
    firstName: _root_.scala.Predef.String,
    lastName: _root_.scala.Predef.String,
    nickName: _root_.scala.Predef.String,
    displayName: _root_.scala.Predef.String,
    preferredLanguage: _root_.scala.Predef.String,
    gender: com.zitadel.user.v1.user.Gender,
    avatarUrl: _root_.scala.Predef.String
  ): _root_.com.zitadel.user.v1.user.Profile = _root_.com.zitadel.user.v1.user.Profile(
    firstName,
    lastName,
    nickName,
    displayName,
    preferredLanguage,
    gender,
    avatarUrl
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[zitadel.user.v1.Profile])
}
