// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.protoc_gen_zitadel.v2.options

@SerialVersionUID(0L)
final case class Options(
    authOption: _root_.scala.Option[com.zitadel.protoc_gen_zitadel.v2.options.AuthOption] = _root_.scala.None,
    httpResponse: _root_.scala.Option[com.zitadel.protoc_gen_zitadel.v2.options.CustomHTTPResponse] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Options] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      if (authOption.isDefined) {
        val __value = authOption.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (httpResponse.isDefined) {
        val __value = httpResponse.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      authOption.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      httpResponse.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def getAuthOption: com.zitadel.protoc_gen_zitadel.v2.options.AuthOption = authOption.getOrElse(com.zitadel.protoc_gen_zitadel.v2.options.AuthOption.defaultInstance)
    def clearAuthOption: Options = copy(authOption = _root_.scala.None)
    def withAuthOption(__v: com.zitadel.protoc_gen_zitadel.v2.options.AuthOption): Options = copy(authOption = Option(__v))
    def getHttpResponse: com.zitadel.protoc_gen_zitadel.v2.options.CustomHTTPResponse = httpResponse.getOrElse(com.zitadel.protoc_gen_zitadel.v2.options.CustomHTTPResponse.defaultInstance)
    def clearHttpResponse: Options = copy(httpResponse = _root_.scala.None)
    def withHttpResponse(__v: com.zitadel.protoc_gen_zitadel.v2.options.CustomHTTPResponse): Options = copy(httpResponse = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => authOption.orNull
        case 2 => httpResponse.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => authOption.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => httpResponse.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: com.zitadel.protoc_gen_zitadel.v2.options.Options.type = com.zitadel.protoc_gen_zitadel.v2.options.Options
    // @@protoc_insertion_point(GeneratedMessage[zitadel.protoc_gen_zitadel.v2.Options])
}

object Options extends scalapb.GeneratedMessageCompanion[com.zitadel.protoc_gen_zitadel.v2.options.Options] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.zitadel.protoc_gen_zitadel.v2.options.Options] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.zitadel.protoc_gen_zitadel.v2.options.Options = {
    var __authOption: _root_.scala.Option[com.zitadel.protoc_gen_zitadel.v2.options.AuthOption] = _root_.scala.None
    var __httpResponse: _root_.scala.Option[com.zitadel.protoc_gen_zitadel.v2.options.CustomHTTPResponse] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __authOption = Option(__authOption.fold(_root_.scalapb.LiteParser.readMessage[com.zitadel.protoc_gen_zitadel.v2.options.AuthOption](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 18 =>
          __httpResponse = Option(__httpResponse.fold(_root_.scalapb.LiteParser.readMessage[com.zitadel.protoc_gen_zitadel.v2.options.CustomHTTPResponse](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    com.zitadel.protoc_gen_zitadel.v2.options.Options(
        authOption = __authOption,
        httpResponse = __httpResponse,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.zitadel.protoc_gen_zitadel.v2.options.Options] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      com.zitadel.protoc_gen_zitadel.v2.options.Options(
        authOption = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[com.zitadel.protoc_gen_zitadel.v2.options.AuthOption]]),
        httpResponse = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[com.zitadel.protoc_gen_zitadel.v2.options.CustomHTTPResponse]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = OptionsProto.javaDescriptor.getMessageTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = OptionsProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = com.zitadel.protoc_gen_zitadel.v2.options.AuthOption
      case 2 => __out = com.zitadel.protoc_gen_zitadel.v2.options.CustomHTTPResponse
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.zitadel.protoc_gen_zitadel.v2.options.Options(
    authOption = _root_.scala.None,
    httpResponse = _root_.scala.None
  )
  implicit class OptionsLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.protoc_gen_zitadel.v2.options.Options]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.zitadel.protoc_gen_zitadel.v2.options.Options](_l) {
    def authOption: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.protoc_gen_zitadel.v2.options.AuthOption] = field(_.getAuthOption)((c_, f_) => c_.copy(authOption = Option(f_)))
    def optionalAuthOption: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.zitadel.protoc_gen_zitadel.v2.options.AuthOption]] = field(_.authOption)((c_, f_) => c_.copy(authOption = f_))
    def httpResponse: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.protoc_gen_zitadel.v2.options.CustomHTTPResponse] = field(_.getHttpResponse)((c_, f_) => c_.copy(httpResponse = Option(f_)))
    def optionalHttpResponse: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.zitadel.protoc_gen_zitadel.v2.options.CustomHTTPResponse]] = field(_.httpResponse)((c_, f_) => c_.copy(httpResponse = f_))
  }
  final val AUTH_OPTION_FIELD_NUMBER = 1
  final val HTTP_RESPONSE_FIELD_NUMBER = 2
  def of(
    authOption: _root_.scala.Option[com.zitadel.protoc_gen_zitadel.v2.options.AuthOption],
    httpResponse: _root_.scala.Option[com.zitadel.protoc_gen_zitadel.v2.options.CustomHTTPResponse]
  ): _root_.com.zitadel.protoc_gen_zitadel.v2.options.Options = _root_.com.zitadel.protoc_gen_zitadel.v2.options.Options(
    authOption,
    httpResponse
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[zitadel.protoc_gen_zitadel.v2.Options])
}
