// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.management.v1.management

@SerialVersionUID(0L)
final case class MigrateGenericOIDCProviderRequest(
    id: _root_.scala.Predef.String = "",
    template: com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template = com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template.Empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[MigrateGenericOIDCProviderRequest] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = id
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      if (template.azure.isDefined) {
        val __value = template.azure.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (template.google.isDefined) {
        val __value = template.google.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = id
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      template.azure.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      template.google.foreach { __v =>
        val __m = __v
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withId(__v: _root_.scala.Predef.String): MigrateGenericOIDCProviderRequest = copy(id = __v)
    def getAzure: com.zitadel.management.v1.management.AddAzureADProviderRequest = template.azure.getOrElse(com.zitadel.management.v1.management.AddAzureADProviderRequest.defaultInstance)
    def withAzure(__v: com.zitadel.management.v1.management.AddAzureADProviderRequest): MigrateGenericOIDCProviderRequest = copy(template = com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template.Azure(__v))
    def getGoogle: com.zitadel.management.v1.management.AddGoogleProviderRequest = template.google.getOrElse(com.zitadel.management.v1.management.AddGoogleProviderRequest.defaultInstance)
    def withGoogle(__v: com.zitadel.management.v1.management.AddGoogleProviderRequest): MigrateGenericOIDCProviderRequest = copy(template = com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template.Google(__v))
    def clearTemplate: MigrateGenericOIDCProviderRequest = copy(template = com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template.Empty)
    def withTemplate(__v: com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template): MigrateGenericOIDCProviderRequest = copy(template = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = id
          if (__t != "") __t else null
        }
        case 2 => template.azure.orNull
        case 3 => template.google.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(id)
        case 2 => template.azure.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => template.google.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.type = com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest
    // @@protoc_insertion_point(GeneratedMessage[zitadel.management.v1.MigrateGenericOIDCProviderRequest])
}

object MigrateGenericOIDCProviderRequest extends scalapb.GeneratedMessageCompanion[com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest = {
    var __id: _root_.scala.Predef.String = ""
    var __template: com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template = com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template.Empty
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __id = _input__.readStringRequireUtf8()
        case 18 =>
          __template = com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template.Azure(__template.azure.fold(_root_.scalapb.LiteParser.readMessage[com.zitadel.management.v1.management.AddAzureADProviderRequest](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 26 =>
          __template = com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template.Google(__template.google.fold(_root_.scalapb.LiteParser.readMessage[com.zitadel.management.v1.management.AddGoogleProviderRequest](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest(
        id = __id,
        template = __template,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest(
        id = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        template = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[com.zitadel.management.v1.management.AddAzureADProviderRequest]]).map(com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template.Azure(_))
            .orElse[com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template](__fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[_root_.scala.Option[com.zitadel.management.v1.management.AddGoogleProviderRequest]]).map(com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template.Google(_)))
            .getOrElse(com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template.Empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ManagementProto.javaDescriptor.getMessageTypes().get(496)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ManagementProto.scalaDescriptor.messages(496)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = com.zitadel.management.v1.management.AddAzureADProviderRequest
      case 3 => __out = com.zitadel.management.v1.management.AddGoogleProviderRequest
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest(
    id = "",
    template = com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template.Empty
  )
  sealed trait Template extends _root_.scalapb.GeneratedOneof {
    def isEmpty: _root_.scala.Boolean = false
    def isDefined: _root_.scala.Boolean = true
    def isAzure: _root_.scala.Boolean = false
    def isGoogle: _root_.scala.Boolean = false
    def azure: _root_.scala.Option[com.zitadel.management.v1.management.AddAzureADProviderRequest] = _root_.scala.None
    def google: _root_.scala.Option[com.zitadel.management.v1.management.AddGoogleProviderRequest] = _root_.scala.None
  }
  object Template {
    @SerialVersionUID(0L)
    case object Empty extends com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template {
      type ValueType = _root_.scala.Nothing
      override def isEmpty: _root_.scala.Boolean = true
      override def isDefined: _root_.scala.Boolean = false
      override def number: _root_.scala.Int = 0
      override def value: _root_.scala.Nothing = throw new java.util.NoSuchElementException("Empty.value")
    }
  
    @SerialVersionUID(0L)
    final case class Azure(value: com.zitadel.management.v1.management.AddAzureADProviderRequest) extends com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template {
      type ValueType = com.zitadel.management.v1.management.AddAzureADProviderRequest
      override def isAzure: _root_.scala.Boolean = true
      override def azure: _root_.scala.Option[com.zitadel.management.v1.management.AddAzureADProviderRequest] = Some(value)
      override def number: _root_.scala.Int = 2
    }
    @SerialVersionUID(0L)
    final case class Google(value: com.zitadel.management.v1.management.AddGoogleProviderRequest) extends com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template {
      type ValueType = com.zitadel.management.v1.management.AddGoogleProviderRequest
      override def isGoogle: _root_.scala.Boolean = true
      override def google: _root_.scala.Option[com.zitadel.management.v1.management.AddGoogleProviderRequest] = Some(value)
      override def number: _root_.scala.Int = 3
    }
  }
  implicit class MigrateGenericOIDCProviderRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest](_l) {
    def id: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.id)((c_, f_) => c_.copy(id = f_))
    def azure: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.management.v1.management.AddAzureADProviderRequest] = field(_.getAzure)((c_, f_) => c_.copy(template = com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template.Azure(f_)))
    def google: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.management.v1.management.AddGoogleProviderRequest] = field(_.getGoogle)((c_, f_) => c_.copy(template = com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template.Google(f_)))
    def template: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template] = field(_.template)((c_, f_) => c_.copy(template = f_))
  }
  final val ID_FIELD_NUMBER = 1
  final val AZURE_FIELD_NUMBER = 2
  final val GOOGLE_FIELD_NUMBER = 3
  def of(
    id: _root_.scala.Predef.String,
    template: com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest.Template
  ): _root_.com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest = _root_.com.zitadel.management.v1.management.MigrateGenericOIDCProviderRequest(
    id,
    template
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[zitadel.management.v1.MigrateGenericOIDCProviderRequest])
}
