version: "3.8"
services:
  postgres:
    container_name: office_buddy_postgres
    restart: always
    image: postgres:14-alpine
    ports:
      - "2345:5432"
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_OFFICE_BUDDY_DATABASE: ${POSTGRES_OFFICE_BUDDY_DATABASE}
      POSTGRES_OFFICE_BUDDY_PASSWORD: ${POSTGRES_OFFICE_BUDDY_PASSWORD}
      POSTGRES_OFFICE_BUDDY_USER: ${POSTGRES_OFFICE_BUDDY_USER}
      POSTGRES_KEYCLOAK_DATABASE: ${POSTGRES_KEYCLOAK_DATABASE}
      POSTGRES_KEYCLOAK_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD}
      POSTGRES_KEYCLOAK_USER: ${POSTGRES_KEYCLOAK_USER}
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  mailpit:
    container_name: office_buddy_mailpit
    restart: always
    image: axllent/mailpit:v1.20
    ports:
      - "8025:8025"
      - "1025:1025"
    healthcheck:
      test: ["CMD", "/mailpit", "readyz"]
      interval: 5s
      timeout: 5s
      retries: 5
  keycloak:
    container_name: office_buddy_keycloak
    restart: always
    image: quay.io/keycloak/keycloak:22.0
    ports:
      - '8888:8080'
    command: [ "start-dev", "--import-realm" ]
    environment:
      KC_DB: postgres
      KC_DB_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD}
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_KEYCLOAK_DATABASE}
      KC_DB_USERNAME: ${POSTGRES_KEYCLOAK_USER}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: true
      OB_SMTP_SERVER_HOST: mailpit
      OB_SMTP_SERVER_PORT: 1025
    volumes:
      - ./keycloak/office-buddy-realm.json:/opt/keycloak/data/import/office-buddy-realm.json
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080; echo -e 'GET /health/ready HTTP/1.1\nHost: localhost:8080\nConnection: close\n\n' >&3;cat <&3 | grep -q '\"status\": \"UP\"' && exit 0 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      postgres:
        condition: 'service_healthy'
      mailpit:
        condition: 'service_healthy'
