version: "3.8"
services:
  postgres:
    restart: always
    image: postgres:14-alpine
    ports:
      - "2345:5432"
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_OFFICE_BUDDY_DATABASE: ${POSTGRES_OFFICE_BUDDY_DATABASE}
      POSTGRES_OFFICE_BUDDY_PASSWORD: ${POSTGRES_OFFICE_BUDDY_PASSWORD}
      POSTGRES_OFFICE_BUDDY_USER: ${POSTGRES_OFFICE_BUDDY_USER}
      POSTGRES_KEYCLOAK_DATABASE: ${POSTGRES_KEYCLOAK_DATABASE}
      POSTGRES_KEYCLOAK_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD}
      POSTGRES_KEYCLOAK_USER: ${POSTGRES_KEYCLOAK_USER}
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  keycloak:
    restart: always
    image: quay.io/keycloak/keycloak:22.0
    ports:
      - '8888:8080'
    command: [ "start-dev" ]
    environment:
      KC_DB: postgres
      KC_DB_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD}
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_KEYCLOAK_DATABASE}
      KC_DB_USERNAME: ${POSTGRES_KEYCLOAK_USER}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      postgres:
        condition: 'service_healthy'
