// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.admin.v1.admin

@SerialVersionUID(0L)
final case class UpdateOIDCSettingsRequest(
    accessTokenLifetime: _root_.scala.Option[com.google.protobuf.duration.Duration] = _root_.scala.None,
    idTokenLifetime: _root_.scala.Option[com.google.protobuf.duration.Duration] = _root_.scala.None,
    refreshTokenIdleExpiration: _root_.scala.Option[com.google.protobuf.duration.Duration] = _root_.scala.None,
    refreshTokenExpiration: _root_.scala.Option[com.google.protobuf.duration.Duration] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[UpdateOIDCSettingsRequest] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      if (accessTokenLifetime.isDefined) {
        val __value = accessTokenLifetime.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (idTokenLifetime.isDefined) {
        val __value = idTokenLifetime.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (refreshTokenIdleExpiration.isDefined) {
        val __value = refreshTokenIdleExpiration.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (refreshTokenExpiration.isDefined) {
        val __value = refreshTokenExpiration.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      accessTokenLifetime.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      idTokenLifetime.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      refreshTokenIdleExpiration.foreach { __v =>
        val __m = __v
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      refreshTokenExpiration.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def getAccessTokenLifetime: com.google.protobuf.duration.Duration = accessTokenLifetime.getOrElse(com.google.protobuf.duration.Duration.defaultInstance)
    def clearAccessTokenLifetime: UpdateOIDCSettingsRequest = copy(accessTokenLifetime = _root_.scala.None)
    def withAccessTokenLifetime(__v: com.google.protobuf.duration.Duration): UpdateOIDCSettingsRequest = copy(accessTokenLifetime = Option(__v))
    def getIdTokenLifetime: com.google.protobuf.duration.Duration = idTokenLifetime.getOrElse(com.google.protobuf.duration.Duration.defaultInstance)
    def clearIdTokenLifetime: UpdateOIDCSettingsRequest = copy(idTokenLifetime = _root_.scala.None)
    def withIdTokenLifetime(__v: com.google.protobuf.duration.Duration): UpdateOIDCSettingsRequest = copy(idTokenLifetime = Option(__v))
    def getRefreshTokenIdleExpiration: com.google.protobuf.duration.Duration = refreshTokenIdleExpiration.getOrElse(com.google.protobuf.duration.Duration.defaultInstance)
    def clearRefreshTokenIdleExpiration: UpdateOIDCSettingsRequest = copy(refreshTokenIdleExpiration = _root_.scala.None)
    def withRefreshTokenIdleExpiration(__v: com.google.protobuf.duration.Duration): UpdateOIDCSettingsRequest = copy(refreshTokenIdleExpiration = Option(__v))
    def getRefreshTokenExpiration: com.google.protobuf.duration.Duration = refreshTokenExpiration.getOrElse(com.google.protobuf.duration.Duration.defaultInstance)
    def clearRefreshTokenExpiration: UpdateOIDCSettingsRequest = copy(refreshTokenExpiration = _root_.scala.None)
    def withRefreshTokenExpiration(__v: com.google.protobuf.duration.Duration): UpdateOIDCSettingsRequest = copy(refreshTokenExpiration = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => accessTokenLifetime.orNull
        case 2 => idTokenLifetime.orNull
        case 3 => refreshTokenIdleExpiration.orNull
        case 4 => refreshTokenExpiration.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => accessTokenLifetime.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => idTokenLifetime.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => refreshTokenIdleExpiration.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 4 => refreshTokenExpiration.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: com.zitadel.admin.v1.admin.UpdateOIDCSettingsRequest.type = com.zitadel.admin.v1.admin.UpdateOIDCSettingsRequest
    // @@protoc_insertion_point(GeneratedMessage[zitadel.admin.v1.UpdateOIDCSettingsRequest])
}

object UpdateOIDCSettingsRequest extends scalapb.GeneratedMessageCompanion[com.zitadel.admin.v1.admin.UpdateOIDCSettingsRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.zitadel.admin.v1.admin.UpdateOIDCSettingsRequest] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.zitadel.admin.v1.admin.UpdateOIDCSettingsRequest = {
    var __accessTokenLifetime: _root_.scala.Option[com.google.protobuf.duration.Duration] = _root_.scala.None
    var __idTokenLifetime: _root_.scala.Option[com.google.protobuf.duration.Duration] = _root_.scala.None
    var __refreshTokenIdleExpiration: _root_.scala.Option[com.google.protobuf.duration.Duration] = _root_.scala.None
    var __refreshTokenExpiration: _root_.scala.Option[com.google.protobuf.duration.Duration] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __accessTokenLifetime = Option(__accessTokenLifetime.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.duration.Duration](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 18 =>
          __idTokenLifetime = Option(__idTokenLifetime.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.duration.Duration](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 26 =>
          __refreshTokenIdleExpiration = Option(__refreshTokenIdleExpiration.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.duration.Duration](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 34 =>
          __refreshTokenExpiration = Option(__refreshTokenExpiration.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.duration.Duration](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    com.zitadel.admin.v1.admin.UpdateOIDCSettingsRequest(
        accessTokenLifetime = __accessTokenLifetime,
        idTokenLifetime = __idTokenLifetime,
        refreshTokenIdleExpiration = __refreshTokenIdleExpiration,
        refreshTokenExpiration = __refreshTokenExpiration,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.zitadel.admin.v1.admin.UpdateOIDCSettingsRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      com.zitadel.admin.v1.admin.UpdateOIDCSettingsRequest(
        accessTokenLifetime = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.duration.Duration]]),
        idTokenLifetime = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.duration.Duration]]),
        refreshTokenIdleExpiration = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.duration.Duration]]),
        refreshTokenExpiration = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.duration.Duration]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = AdminProto.javaDescriptor.getMessageTypes().get(56)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = AdminProto.scalaDescriptor.messages(56)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = com.google.protobuf.duration.Duration
      case 2 => __out = com.google.protobuf.duration.Duration
      case 3 => __out = com.google.protobuf.duration.Duration
      case 4 => __out = com.google.protobuf.duration.Duration
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.zitadel.admin.v1.admin.UpdateOIDCSettingsRequest(
    accessTokenLifetime = _root_.scala.None,
    idTokenLifetime = _root_.scala.None,
    refreshTokenIdleExpiration = _root_.scala.None,
    refreshTokenExpiration = _root_.scala.None
  )
  implicit class UpdateOIDCSettingsRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.admin.v1.admin.UpdateOIDCSettingsRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.zitadel.admin.v1.admin.UpdateOIDCSettingsRequest](_l) {
    def accessTokenLifetime: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.duration.Duration] = field(_.getAccessTokenLifetime)((c_, f_) => c_.copy(accessTokenLifetime = Option(f_)))
    def optionalAccessTokenLifetime: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.duration.Duration]] = field(_.accessTokenLifetime)((c_, f_) => c_.copy(accessTokenLifetime = f_))
    def idTokenLifetime: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.duration.Duration] = field(_.getIdTokenLifetime)((c_, f_) => c_.copy(idTokenLifetime = Option(f_)))
    def optionalIdTokenLifetime: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.duration.Duration]] = field(_.idTokenLifetime)((c_, f_) => c_.copy(idTokenLifetime = f_))
    def refreshTokenIdleExpiration: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.duration.Duration] = field(_.getRefreshTokenIdleExpiration)((c_, f_) => c_.copy(refreshTokenIdleExpiration = Option(f_)))
    def optionalRefreshTokenIdleExpiration: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.duration.Duration]] = field(_.refreshTokenIdleExpiration)((c_, f_) => c_.copy(refreshTokenIdleExpiration = f_))
    def refreshTokenExpiration: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.duration.Duration] = field(_.getRefreshTokenExpiration)((c_, f_) => c_.copy(refreshTokenExpiration = Option(f_)))
    def optionalRefreshTokenExpiration: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.duration.Duration]] = field(_.refreshTokenExpiration)((c_, f_) => c_.copy(refreshTokenExpiration = f_))
  }
  final val ACCESS_TOKEN_LIFETIME_FIELD_NUMBER = 1
  final val ID_TOKEN_LIFETIME_FIELD_NUMBER = 2
  final val REFRESH_TOKEN_IDLE_EXPIRATION_FIELD_NUMBER = 3
  final val REFRESH_TOKEN_EXPIRATION_FIELD_NUMBER = 4
  def of(
    accessTokenLifetime: _root_.scala.Option[com.google.protobuf.duration.Duration],
    idTokenLifetime: _root_.scala.Option[com.google.protobuf.duration.Duration],
    refreshTokenIdleExpiration: _root_.scala.Option[com.google.protobuf.duration.Duration],
    refreshTokenExpiration: _root_.scala.Option[com.google.protobuf.duration.Duration]
  ): _root_.com.zitadel.admin.v1.admin.UpdateOIDCSettingsRequest = _root_.com.zitadel.admin.v1.admin.UpdateOIDCSettingsRequest(
    accessTokenLifetime,
    idTokenLifetime,
    refreshTokenIdleExpiration,
    refreshTokenExpiration
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[zitadel.admin.v1.UpdateOIDCSettingsRequest])
}
