// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.user.v2alpha.auth

sealed abstract class PasskeyAuthenticator(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = PasskeyAuthenticator
  def isPasskeyAuthenticatorUnspecified: _root_.scala.Boolean = false
  def isPasskeyAuthenticatorPlatform: _root_.scala.Boolean = false
  def isPasskeyAuthenticatorCrossPlatform: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[PasskeyAuthenticator] = com.zitadel.user.v2alpha.auth.PasskeyAuthenticator
  final def asRecognized: _root_.scala.Option[com.zitadel.user.v2alpha.auth.PasskeyAuthenticator.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[com.zitadel.user.v2alpha.auth.PasskeyAuthenticator.Recognized])
}

object PasskeyAuthenticator extends _root_.scalapb.GeneratedEnumCompanion[PasskeyAuthenticator] {
  sealed trait Recognized extends PasskeyAuthenticator
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[PasskeyAuthenticator] = this
  
  @SerialVersionUID(0L)
  case object PASSKEY_AUTHENTICATOR_UNSPECIFIED extends PasskeyAuthenticator(0) with PasskeyAuthenticator.Recognized {
    val index = 0
    val name = "PASSKEY_AUTHENTICATOR_UNSPECIFIED"
    override def isPasskeyAuthenticatorUnspecified: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object PASSKEY_AUTHENTICATOR_PLATFORM extends PasskeyAuthenticator(1) with PasskeyAuthenticator.Recognized {
    val index = 1
    val name = "PASSKEY_AUTHENTICATOR_PLATFORM"
    override def isPasskeyAuthenticatorPlatform: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object PASSKEY_AUTHENTICATOR_CROSS_PLATFORM extends PasskeyAuthenticator(2) with PasskeyAuthenticator.Recognized {
    val index = 2
    val name = "PASSKEY_AUTHENTICATOR_CROSS_PLATFORM"
    override def isPasskeyAuthenticatorCrossPlatform: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends PasskeyAuthenticator(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(PASSKEY_AUTHENTICATOR_UNSPECIFIED, PASSKEY_AUTHENTICATOR_PLATFORM, PASSKEY_AUTHENTICATOR_CROSS_PLATFORM)
  def fromValue(__value: _root_.scala.Int): PasskeyAuthenticator = __value match {
    case 0 => PASSKEY_AUTHENTICATOR_UNSPECIFIED
    case 1 => PASSKEY_AUTHENTICATOR_PLATFORM
    case 2 => PASSKEY_AUTHENTICATOR_CROSS_PLATFORM
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = AuthProto.javaDescriptor.getEnumTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = AuthProto.scalaDescriptor.enums(0)
}