// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.policy.v1.policy

sealed abstract class PasswordlessType(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = PasswordlessType
  def isPasswordlessTypeNotAllowed: _root_.scala.Boolean = false
  def isPasswordlessTypeAllowed: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[PasswordlessType] = com.zitadel.policy.v1.policy.PasswordlessType
  final def asRecognized: _root_.scala.Option[com.zitadel.policy.v1.policy.PasswordlessType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[com.zitadel.policy.v1.policy.PasswordlessType.Recognized])
}

object PasswordlessType extends _root_.scalapb.GeneratedEnumCompanion[PasswordlessType] {
  sealed trait Recognized extends PasswordlessType
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[PasswordlessType] = this
  
  @SerialVersionUID(0L)
  case object PASSWORDLESS_TYPE_NOT_ALLOWED extends PasswordlessType(0) with PasswordlessType.Recognized {
    val index = 0
    val name = "PASSWORDLESS_TYPE_NOT_ALLOWED"
    override def isPasswordlessTypeNotAllowed: _root_.scala.Boolean = true
  }
  
  /** PLANNED: PASSWORDLESS_TYPE_WITH_CERT
    */
  @SerialVersionUID(0L)
  case object PASSWORDLESS_TYPE_ALLOWED extends PasswordlessType(1) with PasswordlessType.Recognized {
    val index = 1
    val name = "PASSWORDLESS_TYPE_ALLOWED"
    override def isPasswordlessTypeAllowed: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends PasswordlessType(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(PASSWORDLESS_TYPE_NOT_ALLOWED, PASSWORDLESS_TYPE_ALLOWED)
  def fromValue(__value: _root_.scala.Int): PasswordlessType = __value match {
    case 0 => PASSWORDLESS_TYPE_NOT_ALLOWED
    case 1 => PASSWORDLESS_TYPE_ALLOWED
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = PolicyProto.javaDescriptor.getEnumTypes().get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = PolicyProto.scalaDescriptor.enums(2)
}