// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.settings.v2alpha.settings

sealed abstract class ResourceOwnerType(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = ResourceOwnerType
  def isResourceOwnerTypeUnspecified: _root_.scala.Boolean = false
  def isResourceOwnerTypeInstance: _root_.scala.Boolean = false
  def isResourceOwnerTypeOrg: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[ResourceOwnerType] = com.zitadel.settings.v2alpha.settings.ResourceOwnerType
  final def asRecognized: _root_.scala.Option[com.zitadel.settings.v2alpha.settings.ResourceOwnerType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[com.zitadel.settings.v2alpha.settings.ResourceOwnerType.Recognized])
}

object ResourceOwnerType extends _root_.scalapb.GeneratedEnumCompanion[ResourceOwnerType] {
  sealed trait Recognized extends ResourceOwnerType
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[ResourceOwnerType] = this
  
  @SerialVersionUID(0L)
  case object RESOURCE_OWNER_TYPE_UNSPECIFIED extends ResourceOwnerType(0) with ResourceOwnerType.Recognized {
    val index = 0
    val name = "RESOURCE_OWNER_TYPE_UNSPECIFIED"
    override def isResourceOwnerTypeUnspecified: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RESOURCE_OWNER_TYPE_INSTANCE extends ResourceOwnerType(1) with ResourceOwnerType.Recognized {
    val index = 1
    val name = "RESOURCE_OWNER_TYPE_INSTANCE"
    override def isResourceOwnerTypeInstance: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RESOURCE_OWNER_TYPE_ORG extends ResourceOwnerType(2) with ResourceOwnerType.Recognized {
    val index = 2
    val name = "RESOURCE_OWNER_TYPE_ORG"
    override def isResourceOwnerTypeOrg: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends ResourceOwnerType(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(RESOURCE_OWNER_TYPE_UNSPECIFIED, RESOURCE_OWNER_TYPE_INSTANCE, RESOURCE_OWNER_TYPE_ORG)
  def fromValue(__value: _root_.scala.Int): ResourceOwnerType = __value match {
    case 0 => RESOURCE_OWNER_TYPE_UNSPECIFIED
    case 1 => RESOURCE_OWNER_TYPE_INSTANCE
    case 2 => RESOURCE_OWNER_TYPE_ORG
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = SettingsProto.javaDescriptor.getEnumTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = SettingsProto.scalaDescriptor.enums(0)
}