// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.action.v1.action

sealed abstract class FlowState(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = FlowState
  def isFlowStateUnspecified: _root_.scala.Boolean = false
  def isFlowStateInactive: _root_.scala.Boolean = false
  def isFlowStateActive: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[FlowState] = com.zitadel.action.v1.action.FlowState
  final def asRecognized: _root_.scala.Option[com.zitadel.action.v1.action.FlowState.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[com.zitadel.action.v1.action.FlowState.Recognized])
}

object FlowState extends _root_.scalapb.GeneratedEnumCompanion[FlowState] {
  sealed trait Recognized extends FlowState
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[FlowState] = this
  
  @SerialVersionUID(0L)
  case object FLOW_STATE_UNSPECIFIED extends FlowState(0) with FlowState.Recognized {
    val index = 0
    val name = "FLOW_STATE_UNSPECIFIED"
    override def isFlowStateUnspecified: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object FLOW_STATE_INACTIVE extends FlowState(1) with FlowState.Recognized {
    val index = 1
    val name = "FLOW_STATE_INACTIVE"
    override def isFlowStateInactive: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object FLOW_STATE_ACTIVE extends FlowState(2) with FlowState.Recognized {
    val index = 2
    val name = "FLOW_STATE_ACTIVE"
    override def isFlowStateActive: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends FlowState(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(FLOW_STATE_UNSPECIFIED, FLOW_STATE_INACTIVE, FLOW_STATE_ACTIVE)
  def fromValue(__value: _root_.scala.Int): FlowState = __value match {
    case 0 => FLOW_STATE_UNSPECIFIED
    case 1 => FLOW_STATE_INACTIVE
    case 2 => FLOW_STATE_ACTIVE
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = ActionProto.javaDescriptor.getEnumTypes().get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = ActionProto.scalaDescriptor.enums(2)
}