// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.user.v2alpha.email

@SerialVersionUID(0L)
final case class SetHumanEmail(
    email: _root_.scala.Predef.String = "",
    verification: com.zitadel.user.v2alpha.email.SetHumanEmail.Verification = com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.Empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[SetHumanEmail] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = email
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      if (verification.sendCode.isDefined) {
        val __value = verification.sendCode.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (verification.returnCode.isDefined) {
        val __value = verification.returnCode.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (verification.isVerified.isDefined) {
        val __value = verification.isVerified.get
        __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(4, __value)
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = email
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      verification.sendCode.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      verification.returnCode.foreach { __v =>
        val __m = __v
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      verification.isVerified.foreach { __v =>
        val __m = __v
        _output__.writeBool(4, __m)
      };
      unknownFields.writeTo(_output__)
    }
    def withEmail(__v: _root_.scala.Predef.String): SetHumanEmail = copy(email = __v)
    def getSendCode: com.zitadel.user.v2alpha.email.SendEmailVerificationCode = verification.sendCode.getOrElse(com.zitadel.user.v2alpha.email.SendEmailVerificationCode.defaultInstance)
    def withSendCode(__v: com.zitadel.user.v2alpha.email.SendEmailVerificationCode): SetHumanEmail = copy(verification = com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.SendCode(__v))
    def getReturnCode: com.zitadel.user.v2alpha.email.ReturnEmailVerificationCode = verification.returnCode.getOrElse(com.zitadel.user.v2alpha.email.ReturnEmailVerificationCode.defaultInstance)
    def withReturnCode(__v: com.zitadel.user.v2alpha.email.ReturnEmailVerificationCode): SetHumanEmail = copy(verification = com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.ReturnCode(__v))
    def getIsVerified: _root_.scala.Boolean = verification.isVerified.getOrElse(false)
    def withIsVerified(__v: _root_.scala.Boolean): SetHumanEmail = copy(verification = com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.IsVerified(__v))
    def clearVerification: SetHumanEmail = copy(verification = com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.Empty)
    def withVerification(__v: com.zitadel.user.v2alpha.email.SetHumanEmail.Verification): SetHumanEmail = copy(verification = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = email
          if (__t != "") __t else null
        }
        case 2 => verification.sendCode.orNull
        case 3 => verification.returnCode.orNull
        case 4 => verification.isVerified.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(email)
        case 2 => verification.sendCode.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => verification.returnCode.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 4 => verification.isVerified.map(_root_.scalapb.descriptors.PBoolean(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: com.zitadel.user.v2alpha.email.SetHumanEmail.type = com.zitadel.user.v2alpha.email.SetHumanEmail
    // @@protoc_insertion_point(GeneratedMessage[zitadel.user.v2alpha.SetHumanEmail])
}

object SetHumanEmail extends scalapb.GeneratedMessageCompanion[com.zitadel.user.v2alpha.email.SetHumanEmail] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.zitadel.user.v2alpha.email.SetHumanEmail] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.zitadel.user.v2alpha.email.SetHumanEmail = {
    var __email: _root_.scala.Predef.String = ""
    var __verification: com.zitadel.user.v2alpha.email.SetHumanEmail.Verification = com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.Empty
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __email = _input__.readStringRequireUtf8()
        case 18 =>
          __verification = com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.SendCode(__verification.sendCode.fold(_root_.scalapb.LiteParser.readMessage[com.zitadel.user.v2alpha.email.SendEmailVerificationCode](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 26 =>
          __verification = com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.ReturnCode(__verification.returnCode.fold(_root_.scalapb.LiteParser.readMessage[com.zitadel.user.v2alpha.email.ReturnEmailVerificationCode](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 32 =>
          __verification = com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.IsVerified(_input__.readBool())
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    com.zitadel.user.v2alpha.email.SetHumanEmail(
        email = __email,
        verification = __verification,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.zitadel.user.v2alpha.email.SetHumanEmail] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      com.zitadel.user.v2alpha.email.SetHumanEmail(
        email = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        verification = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[com.zitadel.user.v2alpha.email.SendEmailVerificationCode]]).map(com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.SendCode(_))
            .orElse[com.zitadel.user.v2alpha.email.SetHumanEmail.Verification](__fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[_root_.scala.Option[com.zitadel.user.v2alpha.email.ReturnEmailVerificationCode]]).map(com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.ReturnCode(_)))
            .orElse[com.zitadel.user.v2alpha.email.SetHumanEmail.Verification](__fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).flatMap(_.as[_root_.scala.Option[_root_.scala.Boolean]]).map(com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.IsVerified(_)))
            .getOrElse(com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.Empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = EmailProto.javaDescriptor.getMessageTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = EmailProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = com.zitadel.user.v2alpha.email.SendEmailVerificationCode
      case 3 => __out = com.zitadel.user.v2alpha.email.ReturnEmailVerificationCode
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.zitadel.user.v2alpha.email.SetHumanEmail(
    email = "",
    verification = com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.Empty
  )
  sealed trait Verification extends _root_.scalapb.GeneratedOneof {
    def isEmpty: _root_.scala.Boolean = false
    def isDefined: _root_.scala.Boolean = true
    def isSendCode: _root_.scala.Boolean = false
    def isReturnCode: _root_.scala.Boolean = false
    def isIsVerified: _root_.scala.Boolean = false
    def sendCode: _root_.scala.Option[com.zitadel.user.v2alpha.email.SendEmailVerificationCode] = _root_.scala.None
    def returnCode: _root_.scala.Option[com.zitadel.user.v2alpha.email.ReturnEmailVerificationCode] = _root_.scala.None
    def isVerified: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None
  }
  object Verification {
    @SerialVersionUID(0L)
    case object Empty extends com.zitadel.user.v2alpha.email.SetHumanEmail.Verification {
      type ValueType = _root_.scala.Nothing
      override def isEmpty: _root_.scala.Boolean = true
      override def isDefined: _root_.scala.Boolean = false
      override def number: _root_.scala.Int = 0
      override def value: _root_.scala.Nothing = throw new java.util.NoSuchElementException("Empty.value")
    }
  
    @SerialVersionUID(0L)
    final case class SendCode(value: com.zitadel.user.v2alpha.email.SendEmailVerificationCode) extends com.zitadel.user.v2alpha.email.SetHumanEmail.Verification {
      type ValueType = com.zitadel.user.v2alpha.email.SendEmailVerificationCode
      override def isSendCode: _root_.scala.Boolean = true
      override def sendCode: _root_.scala.Option[com.zitadel.user.v2alpha.email.SendEmailVerificationCode] = Some(value)
      override def number: _root_.scala.Int = 2
    }
    @SerialVersionUID(0L)
    final case class ReturnCode(value: com.zitadel.user.v2alpha.email.ReturnEmailVerificationCode) extends com.zitadel.user.v2alpha.email.SetHumanEmail.Verification {
      type ValueType = com.zitadel.user.v2alpha.email.ReturnEmailVerificationCode
      override def isReturnCode: _root_.scala.Boolean = true
      override def returnCode: _root_.scala.Option[com.zitadel.user.v2alpha.email.ReturnEmailVerificationCode] = Some(value)
      override def number: _root_.scala.Int = 3
    }
    @SerialVersionUID(0L)
    final case class IsVerified(value: _root_.scala.Boolean) extends com.zitadel.user.v2alpha.email.SetHumanEmail.Verification {
      type ValueType = _root_.scala.Boolean
      override def isIsVerified: _root_.scala.Boolean = true
      override def isVerified: _root_.scala.Option[_root_.scala.Boolean] = Some(value)
      override def number: _root_.scala.Int = 4
    }
  }
  implicit class SetHumanEmailLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.user.v2alpha.email.SetHumanEmail]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.zitadel.user.v2alpha.email.SetHumanEmail](_l) {
    def email: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.email)((c_, f_) => c_.copy(email = f_))
    def sendCode: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.user.v2alpha.email.SendEmailVerificationCode] = field(_.getSendCode)((c_, f_) => c_.copy(verification = com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.SendCode(f_)))
    def returnCode: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.user.v2alpha.email.ReturnEmailVerificationCode] = field(_.getReturnCode)((c_, f_) => c_.copy(verification = com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.ReturnCode(f_)))
    def isVerified: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.getIsVerified)((c_, f_) => c_.copy(verification = com.zitadel.user.v2alpha.email.SetHumanEmail.Verification.IsVerified(f_)))
    def verification: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.user.v2alpha.email.SetHumanEmail.Verification] = field(_.verification)((c_, f_) => c_.copy(verification = f_))
  }
  final val EMAIL_FIELD_NUMBER = 1
  final val SEND_CODE_FIELD_NUMBER = 2
  final val RETURN_CODE_FIELD_NUMBER = 3
  final val IS_VERIFIED_FIELD_NUMBER = 4
  def of(
    email: _root_.scala.Predef.String,
    verification: com.zitadel.user.v2alpha.email.SetHumanEmail.Verification
  ): _root_.com.zitadel.user.v2alpha.email.SetHumanEmail = _root_.com.zitadel.user.v2alpha.email.SetHumanEmail(
    email,
    verification
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[zitadel.user.v2alpha.SetHumanEmail])
}
