// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.settings.v2alpha.login_settings

sealed abstract class IdentityProviderType(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = IdentityProviderType
  def isIdentityProviderTypeUnspecified: _root_.scala.Boolean = false
  def isIdentityProviderTypeOidc: _root_.scala.Boolean = false
  def isIdentityProviderTypeJwt: _root_.scala.Boolean = false
  def isIdentityProviderTypeLdap: _root_.scala.Boolean = false
  def isIdentityProviderTypeOauth: _root_.scala.Boolean = false
  def isIdentityProviderTypeAzureAd: _root_.scala.Boolean = false
  def isIdentityProviderTypeGithub: _root_.scala.Boolean = false
  def isIdentityProviderTypeGithubEs: _root_.scala.Boolean = false
  def isIdentityProviderTypeGitlab: _root_.scala.Boolean = false
  def isIdentityProviderTypeGitlabSelfHosted: _root_.scala.Boolean = false
  def isIdentityProviderTypeGoogle: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[IdentityProviderType] = com.zitadel.settings.v2alpha.login_settings.IdentityProviderType
  final def asRecognized: _root_.scala.Option[com.zitadel.settings.v2alpha.login_settings.IdentityProviderType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[com.zitadel.settings.v2alpha.login_settings.IdentityProviderType.Recognized])
}

object IdentityProviderType extends _root_.scalapb.GeneratedEnumCompanion[IdentityProviderType] {
  sealed trait Recognized extends IdentityProviderType
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[IdentityProviderType] = this
  
  @SerialVersionUID(0L)
  case object IDENTITY_PROVIDER_TYPE_UNSPECIFIED extends IdentityProviderType(0) with IdentityProviderType.Recognized {
    val index = 0
    val name = "IDENTITY_PROVIDER_TYPE_UNSPECIFIED"
    override def isIdentityProviderTypeUnspecified: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object IDENTITY_PROVIDER_TYPE_OIDC extends IdentityProviderType(1) with IdentityProviderType.Recognized {
    val index = 1
    val name = "IDENTITY_PROVIDER_TYPE_OIDC"
    override def isIdentityProviderTypeOidc: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object IDENTITY_PROVIDER_TYPE_JWT extends IdentityProviderType(2) with IdentityProviderType.Recognized {
    val index = 2
    val name = "IDENTITY_PROVIDER_TYPE_JWT"
    override def isIdentityProviderTypeJwt: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object IDENTITY_PROVIDER_TYPE_LDAP extends IdentityProviderType(3) with IdentityProviderType.Recognized {
    val index = 3
    val name = "IDENTITY_PROVIDER_TYPE_LDAP"
    override def isIdentityProviderTypeLdap: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object IDENTITY_PROVIDER_TYPE_OAUTH extends IdentityProviderType(4) with IdentityProviderType.Recognized {
    val index = 4
    val name = "IDENTITY_PROVIDER_TYPE_OAUTH"
    override def isIdentityProviderTypeOauth: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object IDENTITY_PROVIDER_TYPE_AZURE_AD extends IdentityProviderType(5) with IdentityProviderType.Recognized {
    val index = 5
    val name = "IDENTITY_PROVIDER_TYPE_AZURE_AD"
    override def isIdentityProviderTypeAzureAd: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object IDENTITY_PROVIDER_TYPE_GITHUB extends IdentityProviderType(6) with IdentityProviderType.Recognized {
    val index = 6
    val name = "IDENTITY_PROVIDER_TYPE_GITHUB"
    override def isIdentityProviderTypeGithub: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object IDENTITY_PROVIDER_TYPE_GITHUB_ES extends IdentityProviderType(7) with IdentityProviderType.Recognized {
    val index = 7
    val name = "IDENTITY_PROVIDER_TYPE_GITHUB_ES"
    override def isIdentityProviderTypeGithubEs: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object IDENTITY_PROVIDER_TYPE_GITLAB extends IdentityProviderType(8) with IdentityProviderType.Recognized {
    val index = 8
    val name = "IDENTITY_PROVIDER_TYPE_GITLAB"
    override def isIdentityProviderTypeGitlab: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object IDENTITY_PROVIDER_TYPE_GITLAB_SELF_HOSTED extends IdentityProviderType(9) with IdentityProviderType.Recognized {
    val index = 9
    val name = "IDENTITY_PROVIDER_TYPE_GITLAB_SELF_HOSTED"
    override def isIdentityProviderTypeGitlabSelfHosted: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object IDENTITY_PROVIDER_TYPE_GOOGLE extends IdentityProviderType(10) with IdentityProviderType.Recognized {
    val index = 10
    val name = "IDENTITY_PROVIDER_TYPE_GOOGLE"
    override def isIdentityProviderTypeGoogle: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends IdentityProviderType(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values = scala.collection.immutable.Seq(IDENTITY_PROVIDER_TYPE_UNSPECIFIED, IDENTITY_PROVIDER_TYPE_OIDC, IDENTITY_PROVIDER_TYPE_JWT, IDENTITY_PROVIDER_TYPE_LDAP, IDENTITY_PROVIDER_TYPE_OAUTH, IDENTITY_PROVIDER_TYPE_AZURE_AD, IDENTITY_PROVIDER_TYPE_GITHUB, IDENTITY_PROVIDER_TYPE_GITHUB_ES, IDENTITY_PROVIDER_TYPE_GITLAB, IDENTITY_PROVIDER_TYPE_GITLAB_SELF_HOSTED, IDENTITY_PROVIDER_TYPE_GOOGLE)
  def fromValue(__value: _root_.scala.Int): IdentityProviderType = __value match {
    case 0 => IDENTITY_PROVIDER_TYPE_UNSPECIFIED
    case 1 => IDENTITY_PROVIDER_TYPE_OIDC
    case 2 => IDENTITY_PROVIDER_TYPE_JWT
    case 3 => IDENTITY_PROVIDER_TYPE_LDAP
    case 4 => IDENTITY_PROVIDER_TYPE_OAUTH
    case 5 => IDENTITY_PROVIDER_TYPE_AZURE_AD
    case 6 => IDENTITY_PROVIDER_TYPE_GITHUB
    case 7 => IDENTITY_PROVIDER_TYPE_GITHUB_ES
    case 8 => IDENTITY_PROVIDER_TYPE_GITLAB
    case 9 => IDENTITY_PROVIDER_TYPE_GITLAB_SELF_HOSTED
    case 10 => IDENTITY_PROVIDER_TYPE_GOOGLE
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = LoginSettingsProto.javaDescriptor.getEnumTypes().get(3)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = LoginSettingsProto.scalaDescriptor.enums(3)
}