// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.settings.v2alpha.settings_service

@SerialVersionUID(0L)
final case class GetActiveIdentityProvidersResponse(
    details: _root_.scala.Option[com.zitadel.`object`.v2alpha.`object`.ListDetails] = _root_.scala.None,
    identityProviders: _root_.scala.Seq[com.zitadel.settings.v2alpha.login_settings.IdentityProvider] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[GetActiveIdentityProvidersResponse] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      if (details.isDefined) {
        val __value = details.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      identityProviders.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      details.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      identityProviders.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def getDetails: com.zitadel.`object`.v2alpha.`object`.ListDetails = details.getOrElse(com.zitadel.`object`.v2alpha.`object`.ListDetails.defaultInstance)
    def clearDetails: GetActiveIdentityProvidersResponse = copy(details = _root_.scala.None)
    def withDetails(__v: com.zitadel.`object`.v2alpha.`object`.ListDetails): GetActiveIdentityProvidersResponse = copy(details = Option(__v))
    def clearIdentityProviders = copy(identityProviders = _root_.scala.Seq.empty)
    def addIdentityProviders(__vs: com.zitadel.settings.v2alpha.login_settings.IdentityProvider *): GetActiveIdentityProvidersResponse = addAllIdentityProviders(__vs)
    def addAllIdentityProviders(__vs: Iterable[com.zitadel.settings.v2alpha.login_settings.IdentityProvider]): GetActiveIdentityProvidersResponse = copy(identityProviders = identityProviders ++ __vs)
    def withIdentityProviders(__v: _root_.scala.Seq[com.zitadel.settings.v2alpha.login_settings.IdentityProvider]): GetActiveIdentityProvidersResponse = copy(identityProviders = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => details.orNull
        case 2 => identityProviders
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => details.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => _root_.scalapb.descriptors.PRepeated(identityProviders.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: com.zitadel.settings.v2alpha.settings_service.GetActiveIdentityProvidersResponse.type = com.zitadel.settings.v2alpha.settings_service.GetActiveIdentityProvidersResponse
    // @@protoc_insertion_point(GeneratedMessage[zitadel.settings.v2alpha.GetActiveIdentityProvidersResponse])
}

object GetActiveIdentityProvidersResponse extends scalapb.GeneratedMessageCompanion[com.zitadel.settings.v2alpha.settings_service.GetActiveIdentityProvidersResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.zitadel.settings.v2alpha.settings_service.GetActiveIdentityProvidersResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.zitadel.settings.v2alpha.settings_service.GetActiveIdentityProvidersResponse = {
    var __details: _root_.scala.Option[com.zitadel.`object`.v2alpha.`object`.ListDetails] = _root_.scala.None
    val __identityProviders: _root_.scala.collection.immutable.VectorBuilder[com.zitadel.settings.v2alpha.login_settings.IdentityProvider] = new _root_.scala.collection.immutable.VectorBuilder[com.zitadel.settings.v2alpha.login_settings.IdentityProvider]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __details = Option(__details.fold(_root_.scalapb.LiteParser.readMessage[com.zitadel.`object`.v2alpha.`object`.ListDetails](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 18 =>
          __identityProviders += _root_.scalapb.LiteParser.readMessage[com.zitadel.settings.v2alpha.login_settings.IdentityProvider](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    com.zitadel.settings.v2alpha.settings_service.GetActiveIdentityProvidersResponse(
        details = __details,
        identityProviders = __identityProviders.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.zitadel.settings.v2alpha.settings_service.GetActiveIdentityProvidersResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      com.zitadel.settings.v2alpha.settings_service.GetActiveIdentityProvidersResponse(
        details = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[com.zitadel.`object`.v2alpha.`object`.ListDetails]]),
        identityProviders = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[com.zitadel.settings.v2alpha.login_settings.IdentityProvider]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = SettingsServiceProto.javaDescriptor.getMessageTypes().get(13)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = SettingsServiceProto.scalaDescriptor.messages(13)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = com.zitadel.`object`.v2alpha.`object`.ListDetails
      case 2 => __out = com.zitadel.settings.v2alpha.login_settings.IdentityProvider
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.zitadel.settings.v2alpha.settings_service.GetActiveIdentityProvidersResponse(
    details = _root_.scala.None,
    identityProviders = _root_.scala.Seq.empty
  )
  implicit class GetActiveIdentityProvidersResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.settings.v2alpha.settings_service.GetActiveIdentityProvidersResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.zitadel.settings.v2alpha.settings_service.GetActiveIdentityProvidersResponse](_l) {
    def details: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.`object`.v2alpha.`object`.ListDetails] = field(_.getDetails)((c_, f_) => c_.copy(details = Option(f_)))
    def optionalDetails: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.zitadel.`object`.v2alpha.`object`.ListDetails]] = field(_.details)((c_, f_) => c_.copy(details = f_))
    def identityProviders: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[com.zitadel.settings.v2alpha.login_settings.IdentityProvider]] = field(_.identityProviders)((c_, f_) => c_.copy(identityProviders = f_))
  }
  final val DETAILS_FIELD_NUMBER = 1
  final val IDENTITY_PROVIDERS_FIELD_NUMBER = 2
  def of(
    details: _root_.scala.Option[com.zitadel.`object`.v2alpha.`object`.ListDetails],
    identityProviders: _root_.scala.Seq[com.zitadel.settings.v2alpha.login_settings.IdentityProvider]
  ): _root_.com.zitadel.settings.v2alpha.settings_service.GetActiveIdentityProvidersResponse = _root_.com.zitadel.settings.v2alpha.settings_service.GetActiveIdentityProvidersResponse(
    details,
    identityProviders
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[zitadel.settings.v2alpha.GetActiveIdentityProvidersResponse])
}
