// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zitadel.management.v1.management

/** @param query
  *  list limitations and ordering
  * @param queries
  *  criteria the client is looking for
  */
@SerialVersionUID(0L)
final case class ListProjectMembersRequest(
    projectId: _root_.scala.Predef.String = "",
    query: _root_.scala.Option[com.zitadel.v1.`object`.ListQuery] = _root_.scala.None,
    queries: _root_.scala.Seq[com.zitadel.member.v1.member.SearchQuery] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ListProjectMembersRequest] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = projectId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      if (query.isDefined) {
        val __value = query.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      queries.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = projectId
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      query.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      queries.foreach { __v =>
        val __m = __v
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withProjectId(__v: _root_.scala.Predef.String): ListProjectMembersRequest = copy(projectId = __v)
    def getQuery: com.zitadel.v1.`object`.ListQuery = query.getOrElse(com.zitadel.v1.`object`.ListQuery.defaultInstance)
    def clearQuery: ListProjectMembersRequest = copy(query = _root_.scala.None)
    def withQuery(__v: com.zitadel.v1.`object`.ListQuery): ListProjectMembersRequest = copy(query = Option(__v))
    def clearQueries = copy(queries = _root_.scala.Seq.empty)
    def addQueries(__vs: com.zitadel.member.v1.member.SearchQuery *): ListProjectMembersRequest = addAllQueries(__vs)
    def addAllQueries(__vs: Iterable[com.zitadel.member.v1.member.SearchQuery]): ListProjectMembersRequest = copy(queries = queries ++ __vs)
    def withQueries(__v: _root_.scala.Seq[com.zitadel.member.v1.member.SearchQuery]): ListProjectMembersRequest = copy(queries = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = projectId
          if (__t != "") __t else null
        }
        case 2 => query.orNull
        case 3 => queries
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(projectId)
        case 2 => query.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => _root_.scalapb.descriptors.PRepeated(queries.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: com.zitadel.management.v1.management.ListProjectMembersRequest.type = com.zitadel.management.v1.management.ListProjectMembersRequest
    // @@protoc_insertion_point(GeneratedMessage[zitadel.management.v1.ListProjectMembersRequest])
}

object ListProjectMembersRequest extends scalapb.GeneratedMessageCompanion[com.zitadel.management.v1.management.ListProjectMembersRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.zitadel.management.v1.management.ListProjectMembersRequest] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.zitadel.management.v1.management.ListProjectMembersRequest = {
    var __projectId: _root_.scala.Predef.String = ""
    var __query: _root_.scala.Option[com.zitadel.v1.`object`.ListQuery] = _root_.scala.None
    val __queries: _root_.scala.collection.immutable.VectorBuilder[com.zitadel.member.v1.member.SearchQuery] = new _root_.scala.collection.immutable.VectorBuilder[com.zitadel.member.v1.member.SearchQuery]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __projectId = _input__.readStringRequireUtf8()
        case 18 =>
          __query = Option(__query.fold(_root_.scalapb.LiteParser.readMessage[com.zitadel.v1.`object`.ListQuery](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 26 =>
          __queries += _root_.scalapb.LiteParser.readMessage[com.zitadel.member.v1.member.SearchQuery](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    com.zitadel.management.v1.management.ListProjectMembersRequest(
        projectId = __projectId,
        query = __query,
        queries = __queries.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.zitadel.management.v1.management.ListProjectMembersRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      com.zitadel.management.v1.management.ListProjectMembersRequest(
        projectId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        query = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[com.zitadel.v1.`object`.ListQuery]]),
        queries = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Seq[com.zitadel.member.v1.member.SearchQuery]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ManagementProto.javaDescriptor.getMessageTypes().get(202)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ManagementProto.scalaDescriptor.messages(202)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = com.zitadel.v1.`object`.ListQuery
      case 3 => __out = com.zitadel.member.v1.member.SearchQuery
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.zitadel.management.v1.management.ListProjectMembersRequest(
    projectId = "",
    query = _root_.scala.None,
    queries = _root_.scala.Seq.empty
  )
  implicit class ListProjectMembersRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.management.v1.management.ListProjectMembersRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.zitadel.management.v1.management.ListProjectMembersRequest](_l) {
    def projectId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.projectId)((c_, f_) => c_.copy(projectId = f_))
    def query: _root_.scalapb.lenses.Lens[UpperPB, com.zitadel.v1.`object`.ListQuery] = field(_.getQuery)((c_, f_) => c_.copy(query = Option(f_)))
    def optionalQuery: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.zitadel.v1.`object`.ListQuery]] = field(_.query)((c_, f_) => c_.copy(query = f_))
    def queries: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[com.zitadel.member.v1.member.SearchQuery]] = field(_.queries)((c_, f_) => c_.copy(queries = f_))
  }
  final val PROJECT_ID_FIELD_NUMBER = 1
  final val QUERY_FIELD_NUMBER = 2
  final val QUERIES_FIELD_NUMBER = 3
  def of(
    projectId: _root_.scala.Predef.String,
    query: _root_.scala.Option[com.zitadel.v1.`object`.ListQuery],
    queries: _root_.scala.Seq[com.zitadel.member.v1.member.SearchQuery]
  ): _root_.com.zitadel.management.v1.management.ListProjectMembersRequest = _root_.com.zitadel.management.v1.management.ListProjectMembersRequest(
    projectId,
    query,
    queries
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[zitadel.management.v1.ListProjectMembersRequest])
}
